Initial CI/CD setup

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -47,8 +47,14 @@ jobs:
         run: |
           echo "Getting IP from Terraform output..."
           ip=$(terraform output -raw instance_public_ip | grep -Eo '([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)')
-          echo "instance_ip=$ip" >> $GITHUB_ENV
-          echo "ip=$ip" >> $GITHUB_OUTPUT
+          echo "Extracted IP: $ip"
+          if [[ ! $ip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+              echo "Error: Invalid IP format detected: $ip"
+              exit 1
+          fi
+          echo "instance_ip=${ip}" > instance_ip.txt
+          cat instance_ip.txt >> $GITHUB_ENV
+          cat instance_ip.txt >> $GITHUB_OUTPUT
           echo "Public IP is: $ip"
 
       - name: Use EC2 IP
